### ISSUE TITLE
support for new woocommerce account page tabbed layout

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/shop-isle#232] opened 2016-07-21 08:48 UTC
question on support: When will Shopisle support the new WooCommerce Account page tabbed layout? It's been several months now...
https://woocommerce.wordpress.com/2016/04/21/tabbed-my-account-pages-in-2-6/

**Comment by ineagu** [comment] 2016-07-21 16:25
@rodica-andronache wasn't this fixed ?

**Comment by rodica-andronache** [comment] 2016-08-03 11:05
Duplicate of https://github.com/Codeinwp/shop-isle/issues/208

**Closed by rodica-andronache** 2016-08-03 11:05 UTC
Labels: duplicate
