### ISSUE TITLE
Slider not responsive

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#276] opened 2016-09-29 01:24 UTC
@rodica-andronache I've noticed this but a user has reported it, just wondering if we have any plans to make it responsive

**Comment by rodica-andronache** [comment] 2016-09-29 11:56
@UVLabs I would need more details here. For me, the slider is responsive.

**Comment by UVLabs** [comment] 2016-09-30 02:43
@rodica-andronache 

Desktop:

http://prntscr.com/co0cge

Mobile:

http://prntscr.com/co0d2q

As you could see there's clearly a difference here only the center of the image is being shown

**Comment by rodica-andronache** [comment] 2016-09-30 07:27
Ok, I understand what you mean. We'll investigate and see if we can do something for this.

**Comment by claudiuvertistudio** [comment] 2016-09-30 11:29
I don't understand the problem here. The screen size is different between desktop and mobile, so the image try to cover all area in slider.
For me looks and works well.

**Comment by UVLabs** [comment] 2016-10-01 21:51
@claudiuvertistudio it's similar to the issue with the issue Zerif slider had (not sure if it was fixed), the slider isn't actually really responsive and we have to tell users to use images where the focus point is in the center or images without any real focus point.

Here is a screenshot from one of the default images:

On desktop: http://prntscr.com/cop2gs
On mobile: http://prntscr.com/cop5f1 as you could see the watch knob is missing also the image looks like it's just been cut on left and right.


Now watch what happens when I use master slider (They have responsive sliders):

On mobile: http://prntscr.com/cop7zv

As you could see those are totally different results and master slider is truly responsive.

**Comment by Basilakis** [comment] 2016-10-05 19:40
@claudiuvertistudio Hey, need an update here please, for client.

Thanks a lot

**Comment by gogogadgetguy** [comment] 2016-10-05 20:24
Hello, can someone please look at this and see if there is a fix? My banners are set up where customers are able to "shop now" by clicking the banner , but they don't even see the area to do that on a mobile phone . Please tell me what the status is for the fix?

**Comment by gogogadgetguy** [comment] 2016-10-05 20:26
@uvlabs @claudiuvertistudio

**Comment by gogogadgetguy** [comment] 2016-10-06 17:27
@uvlabs- can someone please give me an update as to when this will be looked into or fixed it's delaying the launch of my website

**Comment by UVLabs** [comment] 2016-10-06 20:12
@gogogadgetguy we are working on it, we are not able to give you a specific estimate but it might be fixed by next week.

**Comment by gogogadgetguy** [comment] 2016-10-13 14:32
Can i get an update ? It's been a whole week?

**Comment by UVLabs** [comment] 2016-10-17 01:52
@gogogadgetguy I think we decided to not fix this because of how the slider and text overlaying the slider is set up. I believe we spoke to you about this via the support ticket?

@rodica-andronache am I right? Are we going to leave this as is?

**Comment by gogogadgetguy** [comment] 2016-10-17 03:13
I was told to give you the name of the website so you all could help me . 

I'm not understanding why you won't fix though . 

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by gogogadgetguy** [comment] 2016-10-17 13:17
If you're not able to help me , can you at least tell me how you replace the current slider slider

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by rodica-andronache** [comment] 2016-10-17 13:22
Hi @gogogadgetguy ,

Tomorrow @claudiuvertistudio will have a look on this, and will let you know exactly what we can do  here.

Thank you for understanding,
Rodica

**Comment by rodica-andronache** [comment] 2016-10-19 09:14
Hi @gogogadgetguy ,

We investigated this, and decided that the best solution in this case, would be to add an option in the theme, to allow users insert a shortcode for a slider. This way, you would replace the current slider offered by the theme with a slider offered by a plugin of your choice.
This change will be available in the next update of the theme.

Best regards,
Rodica

**Comment by gogogadgetguy** [comment] 2016-10-19 14:44
Can you tell me when this will be available?

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by rodica-andronache** [comment] 2016-10-19 15:44
Hi,

We'll release the update tomorrow.

Regards,
Rodica

**Comment by gogogadgetguy** [comment] 2016-10-19 15:57
Great!

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by gogogadgetguy** [comment] 2016-10-20 11:13
Hello has the update been released?

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by rodica-andronache** [comment] 2016-10-20 15:09
Hi @gogogadgetguy ,

The update is live now. Please let us know if everything is ok.

Regards,
Rodica

**Closed by rodica-andronache** 2016-10-20 15:09 UTC
Labels: investigation

**Comment by gogogadgetguy** [comment] 2016-10-20 15:22
I don’t see that option. Can you tell me where to locate it?

**Comment by rodica-andronache** [comment] 2016-10-20 20:39
Hi @gogogadgetguy ,

The option is available in Appearance -> Customize -> Frontpage sections -> Slider section -> Slider shortcode. http://prntscr.com/cwugtp

Let me know if you manage to see it.

Regards,
Rodica

**Comment by UVLabs** [comment] 2016-10-21 01:46
@gogogadgetguy a good slider would be https://wordpress.org/plugins/master-slider/

**Comment by gogogadgetguy** [comment] 2016-10-25 18:15
Hello I don't see what you see.

Darryl Yates CEO
Gadget Guy Consulting
PR/ Marketing/Communications

323-364-4020
gogogadgetguy@me.com 
http://geraldyates.wix.com/iamdarrylyates

-------------------------------------------------------------------------------------------------- 
PRIVILEGED & CONFIDENTIAL  The information contained in this email message is intended only for use of the person or entity to whom it is addressed. The contained information is CONFIDENTIAL and LEGALLY PRIVILEGED and exempt from disclosure under applicable laws. If you read this message and are not the addressee, you are notified that use, dissemination or reproduction of this message is prohibited. If you have received this message in error, please notify the sender immediately.

On Oct 20, 2016, at 01:39 PM, Rodica-Elena Andronache <notifications@github.com> wrote:

Hi @gogogadgetguy ,
The option is available in Appearance -> Customize -> Frontpage sections -> Slider section -> Slider shortcode. http://prntscr.com/cwugtp
Let me know if you manage to see it.
Regards,
Rodica

**Comment by gogogadgetguy** [comment] 2016-10-25 18:16
I sent screen shots of what I was able to see . I don't see the update that allows the ability to input the short code. 

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com

**Comment by gogogadgetguy** [comment] 2016-10-25 18:20
Great but could you the screenshots 

Thank You.

Please excuse the brevity and pardon any typos.

Respectfully,

Darryl "Gerald" Yates, MBA
323-364-4020
678-464-8713 M
gogogadgetguy@me.com
